apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cloudflared
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.TunnelID | required "Cloudflared TunnelID is required"}}.json: {{ .Values.credentials | toJson | b64enc | quote }}
  credentials.json: {{ .Values.credentials | toJson | b64enc | quote }}
type: Opaque
